### ISSUE TITLE
Dolby Vision target mode HDR10

### ISSUE THREAD

**Issue by KyleSanderson** [cpm-code/xbmc#23]
## Roadmap or todo item
**Detailed Description**
My panel doesn't properly support DoVi. It triggers, but the PQ settings are locked in Firmware.

### Context
If it's possible - I'd like to try going from DoVi to HDR10 as a VS10 target mode. Same deal with HDR10 -> HDR10.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by rome1983** [comment]
Change your Dolby Vision type to Player-led(HDR)
