### ISSUE TITLE
DV p4 issue

### ISSUE THREAD

**Issue by cpm-code** [cpm-code/xbmc#26]
I don't think, if the same issue causes, and not a big thing,  but I have one DV p4 file, which was correct in the A4.1,
 build but now in A5 the movie and the menu looks weird colors.
thanks

[Here is the sample](https://mega.nz/file/KpEhAZZb#CCXfQbhZtZP2npx_ZM7M9t90lK4rqcHoozOIIcPvlaM)

![28](https://github.com/user-attachments/assets/7eb89c73-90d0-48b5-912a-6bb44d9495cf)

_Originally posted by @frodo19 in https://github.com/cpm-code/xbmc/issues/25#issuecomment-2426236128_

**Comment by frodo19** [comment]
Hint. 
Writed a new CE, tested in fresh CE NG nightly, no issue.
A41 build no issue , A5 build weird colours...  seems the EL layer missed, 10 vs 12 bit, 4.2 vs 4.2 FEL

**Comment by chucky88** [comment]
> Hint. Writed a new CE, tested in fresh CE NG nightly, no issue. A41 build no issue , A5 build weird colours... seems the EL layer missed, 10 vs 12 bit, 4.2 vs 4.2 FEL

seems to work for me (correct colors and FEL in stats) in the latest code from ~1hr ago (just compiled and tested), but I'm using LLDV if that matters. Can send you a build to test.

**Comment by frodo19** [comment]
> > Hint. Writed a new CE, tested in fresh CE NG nightly, no issue. A41 build no issue , A5 build weird colours... seems the EL layer missed, 10 vs 12 bit, 4.2 vs 4.2 FEL
> 
> seems to work for me (correct colors and FEL in stats) using the latest WIP code from ~1hr ago (just compiled and tested), but I'm using LLDV if that matters as it might be broken only on TV-Led. Can send you a build to test if you want.

Ok, I can try it.

**Comment by chucky88** [comment]
> > > Hint. Writed a new CE, tested in fresh CE NG nightly, no issue. A41 build no issue , A5 build weird colours... seems the EL layer missed, 10 vs 12 bit, 4.2 vs 4.2 FEL
> > 
> > 
> > seems to work for me (correct colors and FEL in stats) using the latest WIP code from ~1hr ago (just compiled and tested), but I'm using LLDV if that matters as it might be broken only on TV-Led. Can send you a build to test if you want.
> 
> Ok, I can try it.

Here you go. Its based on the latest CE (compared to A5) and CPMs changes:
https://mega.nz/file/RQM2gIrL#INA20YJVRFCUCKN74H5T0zELt8jHbXfxWhSbc6EmIec

**Comment by frodo19** [comment]
Thanks, yo can delete the link. 
I will test later.
