### ISSUE TITLE
Dolby Atmos (EAC3) detection issue in the Player Process Info (A5)

### ISSUE THREAD

**Issue by xNestya** [cpm-code/xbmc#27]
### Describe the bug #1
Hi

When I start the movie in English, the Player Info shows Dolby Atmos (eac3) → My AV receiver shows Dolby Atmos.
Without closing the video, when I switch to the French audio (DD+ 5.1, second audio track), the Player Info shows Dolby Digital Plus 5.1 → My AV receiver shows DD+.

Everything works as expected so far, BUT…

When I start the video with the French audio track, the Player Info shows Dolby Atmos (eac3) → My AV receiver shows DD+.

To get the correct information when I start the video in French, here’s what I have to do:

• Start the video with the French audio track
• Switch the audio track to English
• Switch back to the French audio track to get the correct information in Player Info (Dolby Digital Plus 5.1).

Here is the file that’s causing the issue: [https://mega.nz/file/lZgwxZgB#Myx_r7zXahqDRJSf_5_fLK4s5j_LqHvxOWpBhx83jrc](url)

### Describe the bug #2

I just discovered a new issue with the EAC3 display in the Player Info.

I tried with another movie that has Dolby Atmos (EAC3) and made an interesting discovery.

So, I tried the same manipulation on another movie that doesn’t have a Dolby Atmos audio track, only EAC3.

When I switch between audio streams (for example, from audio track 1 to audio track 3, without closing the video), and then open Player Info, sometimes it displays “Dolby Atmos (eac3),” even if there is no Atmos audio track in the video.

You have to constantly change the audio track to trigger this bug.

Here is the video file that does not have a Dolby Atmos audio track: [https://mega.nz/file/QAowFaDb#oFpb6Ii8Z5IrRNR_yHRoN4NRyviINBPVbFoD5mNYwQI](url)

Sorry for the VLC conversion, there’s a slight signal loss at the beginning of the video.

I am on the Coreelec 21.1.1 (Stable) build / cpm A5.

**Comment by cpm-code** [comment]
Will see if there is a way to improve the detection not expecting to look at it soon as other priorities, so may want to ignore the flag on your skins until get something to try again - maybe in next couple of weeks.
