### ISSUE TITLE
Topic on Coreelec forum closed, time to open own Discourse?

### ISSUE THREAD

**Issue by michelsup** [cpm-code/xbmc#32]
All is said. Coreelec team got a nervous breakdown regarding CPM's builds. I guess it will be the same regarding the skins and everything related to them.
So now the question is: do we need another place to continue the discussion ?
If the answer is yes, and CPM is ok with it, then I will be happy to host a discourse forum myself for the time being.
If the answer is no then you can close the issue.

**Comment by vascobraga41** [comment]
Thanks, that was exactly the goal.

**Comment by michelsup** [comment]
Erf, I forgot about this feature. Now it's about to ask the Coreelec's team to kindly pass the info to their forum's users. I wonder how...

**Comment by Kaan88** [comment]
> Erf, I forgot about this feature. Now it's about to ask the Coreelec's team to kindly pass the info to their forum's users. I wonder how...

Portish kinda already did by linking the issues page here: https://discourse.coreelec.org/t/help-support-cpm-build/52613/572

I'd say that's enough and no need to antogonize the CE team any further.

**Comment by michelsup** [comment]
> no need to antogonize the CE team any further.
Not my aim at all.
