### ISSUE TITLE
SDR 10 not converting to DV

### ISSUE THREAD

**Issue by cferra** [cpm-code/xbmc#37]
Playing a file that shows as SDR 10 using plexmod not triggering DV conversion.  V12

**Comment by cpm-code** [comment]
Not seeing an issue, then again do not use plexmod.

Note: I have seen some ambiguity around identification for SDR10 mixing up with HLG HDR.

Will leave open for now to let other have input who may use plexmod etc.

**Comment by cferra** [comment]
The file I was playing was an old TV show - no HDR.  Are you playing files directly from the file browser?

**Comment by cpm-code** [comment]
Typically from SMB for testing, and Jellyfin for normal usage, and very rarely directly for a connected USB flash for offline usage when taking device out of home.

Not sure why it should matter though, all just a stream of data in the end.

**Comment by liquid-ion** [comment]
I haven't had an issue with SDR10 -> DV. Using PM4K, which shouldn't make a difference anyway.

**Comment by manuelh** [comment]
I'm also using PM4K / Plexmod, and the SDR10 -> DV conversion works for me on the A12 pre-release.

Perhaps it has something to do with your PM4K / Plexmod version. Which version are you using? 

I recommend you get the absolutely latest beta version from the forums: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21-22/481208/3562

**Comment by cpm-code** [comment]
Close as cannot re-produce.
